### ISSUE TITLE
Role Call for contributors

### ISSUE THREAD

**Issue by heckert-gamedev** [abycoder500/Boss-Rush-Jam#5]
Please everyone report in.
I neew your account names on itch.io in order to give you access to the game page while it's still set to "Draft Mode" and to officially tag you as contributors.

I also need your entries for how to list you in the credits so I can replace the dummy data.

**Comment by l0lvers** [comment]
l0lvers- lead project manager, junior game designer 
Or sum like that

**Comment by heckert-gamedev** [comment]
zeebo —  13:07 Uhr
@heckert Redmono 

Role: concept artist, character designer

**Comment by heckert-gamedev** [comment]
Gilgameshh — heute um 22:22 Uhr
@heckert Gilgamesh24

2d game artist

**Comment by abycoder500** [comment]
Aby-artistik

Role: 3d artist

**Comment by nazrud** [comment]
nazrud 3d artist, entvirontment , props

**Comment by Mills2501** [comment]
itch-io username is Mills2501 

Credits can go in as Mills or as Emily Shearwood
Role: composer

**Comment by heckert-gamedev** [comment]
Gabe Mielnik —
it's gabrielmielnik 
[22:59]
I'm doing sound design and a bit of the soundtrack as well

**Comment by heckert-gamedev** [comment]
Submission time is over and the credits are done.
